### ISSUE TITLE
Legacy validator 5.1.0 broken when updating Hl7.Fhir main libraries 5.3.0

### ISSUE THREAD

**Issue by almostchristian** [FirelyTeam/Hl7.Fhir.Validation.Legacy#31]
The latest version of the legacy validators (5.1.0) now fails with the 5.3.0 libraries. It worked with 5.2.0, but changes in 5.3.0 broke binary compatibility with the 5.1.0 validator package.

```
Method not found: 'Hl7.Fhir.ElementModel.Types.DateTime Hl7.Fhir.ElementModel.Types.DateTime.FromDateTimeOffset(System.DateTimeOffset)'.

   at Hl7.Fhir.Validation.MinMaxValidationExtensions.Compare(IComparable instance, Element definition)
   at Hl7.Fhir.Validation.MinMaxValidationExtensions.validateMinMaxValue(Validator me, Element definition, ITypedElement instance, Int32 comparisonOutcome, String elementName)
```

Recompiling the validator solution to use 5.3.0 resolves the issue. I looked at the source code and it seems like DateTime.FromDateTimeOffset was updated with additional optional parameters. Optional parameters are source compatible but they break binary compatibility.  I suggest using the [dotnet package validation](https://learn.microsoft.com/en-us/dotnet/fundamentals/package-validation/overview) to keep track of breaking changes. I have been using them in my nuget packages, and it helps to flag breaking changes from a previous package version in my code.

**Comment by ewoutkramer** [comment]
Yes, indeed, we indeed forgot to republish the validator with the new SDK!  We'll republish it soonish.

We are aware we are not binary compatible, this is not something we try to achieve between minors, as it simply puts too many constraints on our ability to improve the SDK. But I'll take a look at the link you sent - we could use it to avoid unwanted changes and capture changes to the public interface that break compilation (which is what we don't want to happen).

**Comment by ewoutkramer** [comment]
See #2566.

**Comment by mmsmits** [comment]
Validator 5.3.0 has just been released, which includes the newest version of the SDK.
Thanks for reporting @almostchristian
